// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dybhcjmueznnpgggnxoy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR5Ymhjam11ZXpubnBnZ2dueG95Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg1Njg0OTAsImV4cCI6MjA4NDE0NDQ5MH0.fOWxSch-iwgGscysEO8xHiJtdtd5KMaLjOpH4g1pQlU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});